services:
  app:
    build: 
      context: .
    image: app
    container_name: django-app
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - database
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input --clear &&
      gunicorn MovieAPI.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=False
      - DATABASE-NAME=postgres
      - DATABASE-HOST=database
      - DATABASE-PORT=5432
      - DATABASE-USER=postgres
      - DATABASE-PASSWORD=postgres
      
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres    
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data 

  nginx:
    image: nginx:latest
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app         

volumes:
  static:
  media:
  postgres: