# Generated by Django 4.1.5 on 2023-01-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_users_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='users_vote',
            new_name='your_rating',
        ),
    ]
