# Generated by Django 4.1.5 on 2023-01-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_movie_your_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
